# Generated by Django 4.0.6 on 2022-08-14 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('Id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('contatoId', models.IntegerField()),
                ('telefone', models.IntegerField(blank=True, null=True)),
                ('isWhatsapp', models.BooleanField(default=True)),
                ('isTelegram', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('dataUltAlt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dataUltAlt')),
                ('dataCadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dataCadastro')),
            ],
            options={
                'db_table': 'Contato',
            },
        ),
        migrations.CreateModel(
            name='ChaveAcesso',
            fields=[
                ('chaveId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='chaveId')),
                ('advogadoId', models.IntegerField(blank=True, null=True)),
                ('dataUltAlt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dataUltAlt')),
                ('dataAquisicao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dataAquisicao')),
                ('escritorioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Escritorio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ChaveAcesso',
            },
        ),
    ]
