# Generated by Django 4.0.6 on 2022-08-13 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advogado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaveAcesso',
            fields=[
                ('chaveId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='chaveId')),
                ('qtdChaves', models.PositiveSmallIntegerField(verbose_name='qtdChaves')),
                ('dataUltAlt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dataUltAlt')),
                ('dataCadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dataCadastro')),
                ('AdvogadoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Advogado', to='advogado.advogado')),
                ('escritorioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Escritorio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ChaveAcesso',
            },
        ),
    ]
