# Generated by Django 4.0.6 on 2022-07-22 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chaveacesso',
            table='ChaveAcesso',
        ),
    ]
