# Generated by Django 4.0.6 on 2022-08-21 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_alter_planos_funcionalidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planos',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 20, 22, 48, 11, 753873), editable=False, verbose_name='dataCadastro'),
        ),
    ]
