# Generated by Django 4.0.6 on 2022-08-21 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planos',
            fields=[
                ('planoId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='planoId')),
                ('titulo', models.CharField(max_length=50, verbose_name='titulo')),
                ('subtitulo', models.CharField(max_length=100, verbose_name='subtitulo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='valor')),
                ('melhorEscolha', models.BooleanField(default=False, verbose_name='melhorEscolha')),
                ('freqCobranca', models.CharField(choices=[('ME', 'Mensal'), ('AN', 'Anual'), ('VI', 'Vitalicio')], default='ME', max_length=2, verbose_name='freqCobranca')),
                ('funcionalidades', models.CharField(max_length=300, verbose_name='funcionalidades')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('icone', models.CharField(max_length=30, null=True, verbose_name='icone')),
                ('dataInicio', models.DateTimeField(verbose_name='dataInicio')),
                ('dataValidade', models.DateTimeField(verbose_name='dataValidade')),
                ('dataUltAlt', models.DateTimeField(verbose_name='dataUltAlt')),
                ('dataCadastro', models.DateTimeField(editable=False, verbose_name='dataCadastro')),
            ],
            options={
                'db_table': 'Planos',
            },
        ),
        migrations.CreateModel(
            name='ChaveAcesso',
            fields=[
                ('chaveId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='chaveId')),
                ('advogadoId', models.IntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('dataUltAlt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dataUltAlt')),
                ('dataAquisicao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dataAquisicao')),
                ('escritorioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Escritorio', to=settings.AUTH_USER_MODEL)),
                ('planoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Planos', to='gerenciamento.planos')),
            ],
            options={
                'db_table': 'ChaveAcesso',
            },
        ),
    ]
