# Generated by Django 4.0.6 on 2022-08-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planos',
            name='funcionalidades',
            field=models.TextField(max_length=300, verbose_name='funcionalidades'),
        ),
    ]
