# Generated by Django 4.0.6 on 2022-08-28 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0007_alter_chaveacesso_uuid_alter_planos_datacadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planos',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 18, 1, 5, 501852), editable=False, verbose_name='dataCadastro'),
        ),
    ]
