# Generated by Django 5.0.3 on 2024-03-31 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0010_alter_planos_datacadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planos',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 1, 59, 36, 793663), editable=False, verbose_name='dataCadastro'),
        ),
    ]
