# Generated by Django 5.0.3 on 2024-03-31 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0022_alter_planos_datacadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planos',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 11, 44, 48, 555340), editable=False, verbose_name='dataCadastro'),
        ),
    ]
