# Generated by Django 4.0.6 on 2022-07-30 21:42

import apps.escritorio.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escritorio',
            name='cep',
            field=models.CharField(blank=True, max_length=8, validators=[apps.escritorio.validators.validaApenasNumero]),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[apps.escritorio.validators.validaApenasNumero, apps.escritorio.validators.validaCNPJ]),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 30, 18, 42, 18, 735193)),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 30, 18, 42, 18, 735172)),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='email',
            field=models.EmailField(max_length=60, unique=True, validators=[apps.escritorio.validators.validaEmail]),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='numero',
            field=models.IntegerField(blank=True, null=True, validators=[apps.escritorio.validators.validaApenasNumero]),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='qtdChaves',
            field=models.IntegerField(default=0, validators=[apps.escritorio.validators.validaApenasNumero]),
        ),
    ]
