# Generated by Django 4.0.6 on 2022-08-15 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio', '0002_alter_escritorio_datacadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escritorio',
            name='logoPath',
            field=models.ImageField(blank=True, upload_to='media/logo/%d/%m/%Y'),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 0, 12, 18, 946531)),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 0, 12, 18, 946509)),
        ),
    ]
