# Generated by Django 4.0.6 on 2022-08-15 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio', '0003_escritorio_logopath_alter_escritorio_datacadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escritorio',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 0, 16, 42, 594906)),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 0, 16, 42, 594865)),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='logoPath',
            field=models.ImageField(blank=True, upload_to='media/logo/%m/%Y'),
        ),
    ]
