# Generated by Django 4.0.6 on 2022-07-22 04:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio', '0004_alter_escritorio_datacadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escritorio',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 1, 44, 51, 236540)),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='dataUltAlt',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 1, 44, 51, 236522)),
        ),
        migrations.AlterModelTable(
            name='escritorio',
            table='Escritorio',
        ),
    ]
