# Generated by Django 4.0.6 on 2022-08-13 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('advogadoId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('numeroOAB', models.CharField(max_length=9, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nomeAdvogado', models.CharField(max_length=20)),
                ('sobrenomeAdvogado', models.CharField(max_length=40)),
                ('nacionalidade', models.CharField(default='brasileiro', max_length=40)),
                ('estadoCivil', models.CharField(default='solteiro', max_length=20)),
                ('admin', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('dataUltAlt', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataCadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('escritorioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Advogados',
            },
        ),
        migrations.CreateModel(
            name='TrocaSenha',
            fields=[
                ('acessoId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('codAcesso', models.IntegerField()),
                ('primAcesso', models.BooleanField(default=True)),
                ('verificado', models.BooleanField(default=False)),
                ('tipoTroca', models.IntegerField(choices=[(1, 'PrimeiroAcesso'), (2, 'EsqueceuSenha')], default=1)),
                ('dataUltAlt', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataCadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('advogadoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advogado.advogado')),
            ],
            options={
                'db_table': 'TrocaSenha',
            },
        ),
    ]
