# Generated by Django 4.0.6 on 2022-08-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advogado',
            old_name='numeroOAB',
            new_name='oab',
        ),
        migrations.RenameField(
            model_name='advogado',
            old_name='nomeAdvogado',
            new_name='primeiroNome',
        ),
        migrations.RenameField(
            model_name='advogado',
            old_name='sobrenomeAdvogado',
            new_name='sobrenome',
        ),
        migrations.RemoveField(
            model_name='advogado',
            name='login',
        ),
    ]
