# Generated by Django 4.0.6 on 2022-08-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advogado',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
    ]
