# Generated by Django 4.0.6 on 2022-08-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0002_alter_advogado_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='advogado',
            name='fotoPath',
            field=models.ImageField(blank=True, upload_to='media/foto/%d/%m/%Y'),
        ),
    ]
