# Generated by Django 4.0.6 on 2022-08-28 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advogado', '0003_alter_contato_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='Id',
            new_name='contatoId',
        ),
    ]
