# Generated by Django 5.0.3 on 2024-03-31 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarenciasLei91',
            fields=[
                ('carenciaId', models.AutoField(primary_key=True, serialize=False)),
                ('dataImplemento', models.DateField()),
                ('tempoContribuicao', models.IntegerField()),
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2024, 3, 31, 11, 44, 47, 212356))),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2024, 3, 31, 11, 44, 47, 212369))),
            ],
            options={
                'db_table': 'CarenciasLei91',
            },
        ),
        migrations.CreateModel(
            name='ConvMon',
            fields=[
                ('convMonId', models.AutoField(primary_key=True, serialize=False)),
                ('nomeMoeda', models.CharField(max_length=20)),
                ('fator', models.BigIntegerField()),
                ('dataInicial', models.DateField()),
                ('dataFinal', models.DateField(blank=True, null=True)),
                ('conversao', models.CharField(choices=[('V', 'Valorizou'), ('D', 'Desvalorizou')], default='V', max_length=1)),
                ('moedaCorrente', models.BooleanField(default=False)),
                ('sinal', models.CharField(max_length=10)),
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2024, 3, 31, 11, 44, 47, 211562))),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2024, 3, 31, 11, 44, 47, 211575))),
            ],
            options={
                'db_table': 'ConvMon',
            },
        ),
        migrations.CreateModel(
            name='TetosPrev',
            fields=[
                ('tetosPrevId', models.AutoField(primary_key=True, serialize=False)),
                ('dataValidade', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=19)),
                ('dataUltAlt', models.DateTimeField(default=datetime.datetime(2024, 3, 31, 11, 44, 47, 212014))),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2024, 3, 31, 11, 44, 47, 212030))),
            ],
            options={
                'db_table': 'TetosPrev',
            },
        ),
    ]
