# Generated by Django 5.0.3 on 2024-03-31 14:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('advogadoId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('primeiroNome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('senha', models.CharField(max_length=30)),
                ('numeroOAB', models.CharField(max_length=9, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nacionalidade', models.CharField(default='brasileiro', max_length=40)),
                ('estadoCivil', models.CharField(default='solteiro', max_length=20)),
                ('admin', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('fotoPath', models.ImageField(blank=True, upload_to='foto/%Y/%m')),
                ('dataUltAlt', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataCadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('escritorioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Advogados',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('contatoId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('telefone', models.CharField(blank=True, max_length=13, null=True)),
                ('isWhatsapp', models.BooleanField(default=True)),
                ('isTelegram', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('dataUltAlt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dataUltAlt')),
                ('dataCadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dataCadastro')),
                ('advogadoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advogado.advogado')),
            ],
            options={
                'db_table': 'Contato',
            },
        ),
        migrations.CreateModel(
            name='EnderecoAdvogado',
            fields=[
                ('enderecoId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('endereco', models.CharField(max_length=60)),
                ('cidade', models.CharField(max_length=60)),
                ('estado', models.CharField(max_length=60)),
                ('bairro', models.CharField(max_length=60)),
                ('cep', models.IntegerField()),
                ('numero', models.CharField(max_length=60)),
                ('complemento', models.CharField(max_length=60)),
                ('dataUltAlt', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataCadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('advogadoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advogado.advogado')),
            ],
            options={
                'db_table': 'EnderecoAdvogado',
            },
        ),
        migrations.CreateModel(
            name='TrocaSenha',
            fields=[
                ('acessoId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('codAcesso', models.IntegerField()),
                ('primAcesso', models.BooleanField(default=True)),
                ('verificado', models.BooleanField(default=False)),
                ('tipoTroca', models.IntegerField(choices=[(1, 'PrimeiroAcesso'), (2, 'EsqueceuSenha')], default=1)),
                ('dataUltAlt', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataCadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('advogadoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advogado.advogado')),
            ],
            options={
                'db_table': 'TrocaSenha',
            },
        ),
    ]
